# Golden Hour Light — warm light with deep amber, forest, navy accents
# Palette: bg=#e4d8c8, fg=#302620, amber=#a06820, forest=#3a6a18, navy=#38608a, plum=#7a3860

typeset -g POWERLEVEL9K_DIR_FOREGROUND=94         # deep amber-brown
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=137  # muted tan
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=124  # red

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=28    # forest green
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=28
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=166 # burnt orange
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=28

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=130  # rich amber
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=124  # deep red

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=96   # plum
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=28
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=28
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=124
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=124
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=124

typeset -g POWERLEVEL9K_CHEZMOI_SHELL_FOREGROUND=124  # red

# Git formatter colors (formatter itself lives in ~/.p10k.zsh)
typeset -g MY_GIT_COLOR_META='%f'
typeset -g MY_GIT_COLOR_CLEAN='%28F'  # forest green
typeset -g MY_GIT_COLOR_MODIFIED='%166F'  # burnt orange
typeset -g MY_GIT_COLOR_UNTRACKED='%94F'  # amber-brown
typeset -g MY_GIT_COLOR_CONFLICTED='%124F'  # deep red
