# Golden Hour — warm darks with amber, rust, sage accents
# Palette: bg=#1a1520, amber=#d4a458, rust=#d07068, sage=#8ab070, blue=#7088aa, mauve=#b880a0

typeset -g POWERLEVEL9K_DIR_FOREGROUND=137        # warm amber-tan
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=95   # muted mauve
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=179  # bright amber

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=107   # sage green
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=107
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=215 # warm orange
typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_COLOR=107

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=179  # amber
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=167  # rust

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=139  # dusty mauve
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=107
typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=107
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=167
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=167
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=167

typeset -g POWERLEVEL9K_CHEZMOI_SHELL_FOREGROUND=167  # rust-red

# Git formatter colors (formatter itself lives in ~/.p10k.zsh)
typeset -g MY_GIT_COLOR_META='%f'
typeset -g MY_GIT_COLOR_CLEAN='%107F'  # sage green
typeset -g MY_GIT_COLOR_MODIFIED='%215F'  # warm orange
typeset -g MY_GIT_COLOR_UNTRACKED='%137F'  # amber-tan
typeset -g MY_GIT_COLOR_CONFLICTED='%167F'  # rust
