# Generate mako's colour include (~/.config/mako/theme) from a theme palette.
#
# mako has no theme concept, but its config can `include=` another file, so
# the colours live in a generated file that ~/.config/mako/config includes and
# everything else (geometry, font, timeouts, modes) stays in chezmoi. chezmoi
# ships a default copy (dot_config/mako/create_theme) that it creates once and
# never overwrites, so rewrites here are not drift.
#
# The look is the "frosted" card: a translucent theme surface that Hyprland
# blurs behind (layer rule in hyprland.lua), a hairline border, an app line in
# the app's accent, a bold summary and a dimmer body. Attention (critical)
# toasts take the theme's caution colour for the border and app line.

mako_theme_error=""

# Hex alpha for a 0-100 opacity, since mako colours are #RRGGBBAA.
mako_alpha() {
  printf '%02x' $(( $1 * 255 / 100 ))
}

mako_generate_theme() {
  local palette_file="$1"
  local theme_slug="$2"
  local theme_mode="$3"
  local destination="$4"
  local bg text accent caution dim surface_alpha border claude_ink
  local destination_dir temporary

  mako_theme_error=""

  if [[ ! -f "$palette_file" ]]; then
    mako_theme_error="palette not found: $palette_file"
    return 1
  fi

  # A missing token is an empty string, not a failure: callers may run
  # under errexit, and css_var's grep exits 1 on no match.
  bg=$(css_var "$palette_file" background-solid) || true
  text=$(css_var "$palette_file" text-primary) || true
  accent=$(css_var "$palette_file" accent) || true
  caution=$(css_var "$palette_file" system-caution) || true
  [[ -n "$caution" ]] || caution=$(css_var "$palette_file" system-critical) || true
  [[ -n "$caution" ]] || caution="$accent"

  if [[ -z "$bg" || -z "$text" || -z "$accent" ]]; then
    mako_theme_error="palette is missing a required solid color"
    return 1
  fi

  bg=$(norm_hex "$bg"); text=$(norm_hex "$text")
  accent=$(norm_hex "$accent"); caution=$(norm_hex "$caution")
  dim=$(mix "$text" "$bg" 25)

  # Light cards need more opacity to hold text contrast over a busy
  # wallpaper; the border is a white glint on light and a faint ink line on
  # dark, as frosted glass reads in each.
  case "$theme_mode" in
    light)
      surface_alpha=$(mako_alpha 72)
      border="ffffff$(mako_alpha 70)"
      claude_ink=c96442
      ;;
    dark)
      surface_alpha=$(mako_alpha 66)
      border="$text$(mako_alpha 14)"
      claude_ink=e08a6a
      ;;
    *)
      mako_theme_error="invalid color scheme: $theme_mode"
      return 1
      ;;
  esac

  destination_dir=${destination%/*}
  mkdir -p "$destination_dir" || {
    mako_theme_error="cannot create destination directory: $destination_dir"
    return 1
  }
  temporary=$(mktemp "$destination.XXXXXX") || {
    mako_theme_error="cannot create temporary theme file"
    return 1
  }

  # The format lines are Pango markup; %a and %s arrive escaped, %b is the
  # sender's own markup (agent-notify escapes what it sends).
  if ! cat >"$temporary" <<EOF
# Generated by set-theme.sh from $theme_slug ($theme_mode) — do not edit.
# Regenerate with: set-theme $theme_slug
# Included from ~/.config/mako/config, which holds everything but colour.
background-color=#$bg$surface_alpha
text-color=#$text
border-color=#$border
progress-color=over #$accent$(mako_alpha 40)
format=<span size="8.5pt" weight="600" foreground="#$accent">%a</span>\n<span size="10pt" weight="600">%s</span>\n<span foreground="#$dim">%b</span>

# Agent toasts (~/.local/bin/agent-notify): each app line in its own ink.
[app-name=Claude]
format=<span size="8.5pt" weight="600" foreground="#$claude_ink">%a</span>\n<span size="10pt" weight="600">%s</span>\n<span foreground="#$dim">%b</span>

[app-name=Codex]
format=<span size="8.5pt" weight="600" foreground="#$text">%a</span>\n<span size="10pt" weight="600">%s</span>\n<span foreground="#$dim">%b</span>

# Last, so it wins over the per-app lines: anything waiting on the user.
[urgency=critical]
border-color=#$caution
format=<span size="8.5pt" weight="600" foreground="#$caution">%a</span>\n<span size="10pt" weight="600">%s</span>\n<span foreground="#$dim">%b</span>

[hidden]
format=<span size="8.5pt" foreground="#$dim">+%h more</span>
EOF
  then
    rm -f -- "$temporary"
    mako_theme_error="cannot write theme file"
    return 1
  fi

  # mktemp creates 0600; chezmoi manages this path (create_theme) as 0644, and
  # a mode change would show up as drift even though content never does.
  chmod 644 -- "$temporary"
  mv -f -- "$temporary" "$destination" || {
    rm -f -- "$temporary"
    mako_theme_error="cannot replace $destination"
    return 1
  }
}
