# Generate the custom stylesheet consumed by YouTube Music Desktop App.
#
# The app is an Electron wrapper around music.youtube.com, so its supported
# theming seam is a CSS file. Keep the palette derivation here and the app
# configuration in chezmoi; callers only choose a desktop theme and target.

youtube_music_theme_error=""

youtube_music_generate_theme() {
  local palette_file="$1"
  local theme_slug="$2"
  local theme_mode="$3"
  local destination="$4"
  local bg accent accent_light text text_dim surface raised border on_accent
  local destination_dir temporary

  youtube_music_theme_error=""

  if [[ ! -f "$palette_file" ]]; then
    youtube_music_theme_error="palette not found: $palette_file"
    return 1
  fi

  case "$theme_mode" in
    light|dark) ;;
    *)
      youtube_music_theme_error="invalid color scheme: $theme_mode"
      return 1
      ;;
  esac

  bg=$(css_var "$palette_file" background-solid)
  accent=$(css_var "$palette_file" accent)
  accent_light=$(css_var "$palette_file" accent-light)
  text=$(css_var "$palette_file" text-primary)
  text_dim=$(css_var "$palette_file" text-secondary)

  if [[ -z "$bg" || -z "$accent" || -z "$text" || -z "$text_dim" ]]; then
    youtube_music_theme_error="palette is missing a required solid color"
    return 1
  fi

  [[ -n "$accent_light" ]] || accent_light="$accent"
  surface=$(mix "$bg" "$text" 10)
  raised=$(mix "$bg" "$text" 16)
  border=$(mix "$bg" "$text_dim" 28)
  on_accent=$(pick_readable "$accent" "$bg" "$text")

  destination_dir=${destination%/*}
  mkdir -p "$destination_dir" || {
    youtube_music_theme_error="cannot create destination directory: $destination_dir"
    return 1
  }
  temporary=$(mktemp "$destination.XXXXXX") || {
    youtube_music_theme_error="cannot create temporary stylesheet"
    return 1
  }

  if ! cat >"$temporary" <<EOF
/* Generated by set-theme.sh from $theme_slug — do not edit. */

html:not(.style-scope) {
  color-scheme: $theme_mode;

  --desktop-theme-background: $bg;
  --desktop-theme-surface: #$surface;
  --desktop-theme-raised: #$raised;
  --desktop-theme-border: #$border;
  --desktop-theme-accent: $accent;
  --desktop-theme-accent-hover: $accent_light;
  --desktop-theme-text: $text;
  --desktop-theme-text-dim: $text_dim;
  --desktop-theme-on-accent: #$on_accent;

  /* YouTube Music's stable theme variables. The explicit component rules
     below cover releases that still hard-code part of the Polymer shell. */
  --ytmusic-color-black1: var(--desktop-theme-background) !important;
  --ytmusic-color-black2: var(--desktop-theme-surface) !important;
  --ytmusic-color-black3: var(--desktop-theme-raised) !important;
  --ytmusic-color-grey1: var(--desktop-theme-text-dim) !important;
  --ytmusic-color-grey2: var(--desktop-theme-text) !important;
  --ytmusic-color-white1: var(--desktop-theme-text) !important;
  --ytmusic-primary-text-color: var(--desktop-theme-text) !important;
  --ytmusic-secondary-text-color: var(--desktop-theme-text-dim) !important;
  --ytmusic-detail-header: var(--desktop-theme-background) !important;
  --ytmusic-dialog-background-color: var(--desktop-theme-raised) !important;
  --ytmusic-nav-bar: var(--desktop-theme-surface) !important;
  --ytmusic-player-bar-background: var(--desktop-theme-surface) !important;
  --ytmusic-brand-link-text: var(--desktop-theme-accent) !important;
  --ytmusic-focus-active: var(--desktop-theme-accent) !important;
  --yt-spec-base-background: var(--desktop-theme-background) !important;
  --yt-spec-raised-background: var(--desktop-theme-raised) !important;
  --yt-spec-menu-background: var(--desktop-theme-raised) !important;
  --yt-spec-brand-background-primary: var(--desktop-theme-background) !important;
  --yt-spec-brand-background-secondary: var(--desktop-theme-surface) !important;
  --yt-spec-text-primary: var(--desktop-theme-text) !important;
  --yt-spec-text-secondary: var(--desktop-theme-text-dim) !important;
  --yt-spec-themed-blue: var(--desktop-theme-accent) !important;
  --yt-spec-call-to-action: var(--desktop-theme-accent) !important;
}

body,
ytmusic-app,
ytmusic-player-page,
ytmusic-detail-header-renderer,
ytmusic-list-item-renderer,
ytmusic-responsive-list-item-renderer,
ytmusic-player-queue-item {
  background-color: var(--desktop-theme-background) !important;
  color: var(--desktop-theme-text) !important;
}

ytmusic-nav-bar,
ytmusic-player-bar,
#player-bar-background.ytmusic-app-layout,
ytmusic-data-bound-header-renderer,
ytmusic-tabs.stuck,
ytmusic-search-box[opened] #suggestion-list,
ytmusic-search-suggestions-section,
ytmusic-menu-popup-renderer,
tp-yt-paper-listbox,
tp-yt-paper-toast,
ytd-multi-page-menu-renderer {
  background-color: var(--desktop-theme-surface) !important;
  color: var(--desktop-theme-text) !important;
}

ytmusic-dialog,
ytmusic-settings-page,
tp-yt-paper-dialog,
.dropdown-content {
  background-color: var(--desktop-theme-raised) !important;
  color: var(--desktop-theme-text) !important;
  border-color: var(--desktop-theme-border) !important;
}

yt-formatted-string,
ytmusic-pivot-bar-item-renderer,
ytmusic-search-box input,
ytmusic-search-suggestion,
.title,
.subtitle,
.description,
.time-info {
  color: var(--desktop-theme-text) !important;
}

.subtitle,
.secondary-flex-columns,
.strapline,
.description,
.time-info {
  color: var(--desktop-theme-text-dim) !important;
}

a,
ytmusic-pivot-bar-item-renderer:hover,
ytmusic-pivot-bar-item-renderer.iron-selected,
ytmusic-like-button-renderer,
ytmusic-menu-navigation-item-renderer,
ytmusic-toggle-menu-service-item-renderer {
  color: var(--desktop-theme-accent) !important;
  --iron-icon-fill-color: var(--desktop-theme-accent) !important;
  --icon-color: var(--desktop-theme-accent) !important;
}

#progress-bar.ytmusic-player-bar,
tp-yt-paper-slider#progress-bar.ytmusic-player-bar {
  --paper-slider-active-color: var(--desktop-theme-accent) !important;
  --paper-slider-knob-color: var(--desktop-theme-accent) !important;
  --paper-slider-container-color: var(--desktop-theme-border) !important;
}

yt-button-renderer[is-paper-button],
.content-wrapper.ytmusic-play-button-renderer,
.previous-items-button.ytmusic-carousel,
.next-items-button.ytmusic-carousel {
  background-color: var(--desktop-theme-accent) !important;
  color: var(--desktop-theme-on-accent) !important;
  --ytmusic-play-button-icon-color: var(--desktop-theme-on-accent) !important;
}

::-webkit-scrollbar-thumb {
  background-color: var(--desktop-theme-border) !important;
}

::selection {
  background: var(--desktop-theme-accent) !important;
  color: var(--desktop-theme-on-accent) !important;
}
EOF
  then
    rm -f -- "$temporary"
    youtube_music_theme_error="cannot write temporary stylesheet"
    return 1
  fi

  if ! mv -f -- "$temporary" "$destination"; then
    rm -f -- "$temporary"
    youtube_music_theme_error="cannot install stylesheet: $destination"
    return 1
  fi
}
