# Tokyo Night
# Cool, neon-lit dark blue-purple theme inspired by Tokyo at night

[meta]
version = 1
name = "Tokyo Night"
description = "Cool, neon-lit dark blue-purple theme inspired by Tokyo at night"
variant = "dark"

[colors.core]
background = "#1A1B26"
foreground = "#A9B1D6"
secondary_background = "#24283B"
border = "#414868"
accent = "#7AA2F7"

[colors.accents]
blue = "#7AA2F7"
green = "#9ECE6A"
magenta = "#AD8EE6"
orange = "#EB927B"
purple = "#AD8EE6"
red = "#F7768E"
yellow = "#E0AF68"
cyan = "#449DAB"

[colors.list.item.selection]
background = { name = "#292E42", opacity = 0.8 }
secondary_background = "#24283B"

[colors.list.item.hover]
background = { name = "#414868", opacity = 0.35 }
