#!/usr/bin/env bash

set -euo pipefail

test_root=$(mktemp -d "${TMPDIR:-/tmp}/mako-theme.XXXXXX")

cleanup() {
  [[ "$test_root" == */mako-theme.* ]] && rm -rf -- "$test_root"
}
trap cleanup EXIT

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=lib/theme-colors.sh
source "$script_dir/lib/theme-colors.sh"
# shellcheck source=lib/mako-theme.sh
source "$script_dir/lib/mako-theme.sh"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

# Asserts one exact line is present, so a colour cannot pass by appearing in
# some other option.
has_line() {
  grep -Fxq -- "$2" "$1" || fail "missing line in ${1##*/}: $2"
}

palette="$test_root/palette.css"
cat >"$palette" <<'EOF'
:root {
  --background-solid: #292e39;
  --accent: #88c0d0;
  --text-primary: #eceff4;
  --text-secondary: #d8dee9;
  --system-caution: #ebcb8b;
  --system-critical: #bf616a;
}
EOF

# Dark: translucent theme surface (0.66), faint ink border, caution for
# critical toasts, and the sections mako needs in a valid order.
target="$test_root/mako/theme"
mako_generate_theme "$palette" "test-night" "dark" "$target"
[[ -f "$target" ]] || fail "dark theme not written"
[[ $(ls -l "$target" | cut -c1-10) == "-rw-r--r--" ]] || fail "theme file is not 0644 (chezmoi would report drift)"
has_line "$target" "background-color=#292e39a8"
has_line "$target" "text-color=#eceff4"
has_line "$target" "border-color=#eceff423"
has_line "$target" "border-color=#ebcb8b"
grep -Fq 'Generated by set-theme.sh from test-night (dark)' "$target" \
  || fail "header does not name the theme"
grep -Fq 'foreground="#88c0d0">%a<' "$target" || fail "app line is not the accent"
grep -Fq 'foreground="#ebcb8b">%a<' "$target" || fail "critical app line is not caution"
[[ $(grep -c '^\[' "$target") -eq 4 ]] || fail "expected 4 criteria sections"
# Critical must come after the per-app sections, or their format would win.
[[ $(grep -n '^\[urgency=critical\]' "$target" | cut -d: -f1) -gt \
   $(grep -n '^\[app-name=Codex\]' "$target" | cut -d: -f1) ]] \
  || fail "urgency=critical is not after the app sections"
# Every non-comment line outside a section must be key=value (mako rejects
# the whole config otherwise).
if grep -vE '^(#.*|\[.*\]|[a-z-]+=.+|)$' "$target"; then
  fail "malformed line in generated theme"
fi

# Light: more opaque surface (0.72) and a white glint border.
light_target="$test_root/light"
mako_generate_theme "$palette" "test-day" "light" "$light_target"
has_line "$light_target" "background-color=#292e39b7"
has_line "$light_target" "border-color=#ffffffb2"

# Caution falls back to critical, then to the accent.
sed '/system-caution/d' "$palette" >"$test_root/no-caution.css"
mako_generate_theme "$test_root/no-caution.css" "fallback" "dark" "$test_root/fallback"
has_line "$test_root/fallback" "border-color=#bf616a"
sed '/system-/d' "$palette" >"$test_root/no-system.css"
mako_generate_theme "$test_root/no-system.css" "fallback" "dark" "$test_root/fallback2"
has_line "$test_root/fallback2" "border-color=#88c0d0"

# Rejections leave any existing file untouched.
echo "sentinel" >"$test_root/existing"
if mako_generate_theme "$test_root/no-such.css" "missing" "dark" "$test_root/existing"; then
  fail "missing palette was accepted"
fi
[[ "$mako_theme_error" == "palette not found:"* ]] || fail "wrong error: $mako_theme_error"
if mako_generate_theme "$palette" "invalid" "sepia" "$test_root/existing"; then
  fail "invalid color scheme was accepted"
fi
printf '%s\n' '--accent: #fff;' >"$test_root/malformed.css"
if mako_generate_theme "$test_root/malformed.css" "malformed" "dark" "$test_root/existing"; then
  fail "palette without a background was accepted"
fi
[[ $(cat "$test_root/existing") == "sentinel" ]] || fail "rejected run modified the target"
[[ -z $(find "$test_root" -name 'existing.*') ]] || fail "temporary file left behind"

echo "mako theme tests passed"
