#!/usr/bin/env bash

set -euo pipefail

test_root=$(mktemp -d "${TMPDIR:-/tmp}/typora-theme.XXXXXX")

cleanup() {
  [[ "$test_root" == */typora-theme.* ]] && rm -rf -- "$test_root"
}
trap cleanup EXIT

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=lib/theme-colors.sh
source "$script_dir/lib/theme-colors.sh"
# shellcheck source=lib/typora-theme.sh
source "$script_dir/lib/typora-theme.sh"

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

# Isolate from any real Typora: never treat the test host's app as running.
typora_theme_running() { return 1; }

decode() { typora_profile_decode "$1"; }
encode_json() { printf '%s' "$1" | typora_profile_encode; }

# --- Generation -------------------------------------------------------------

palette="$test_root/palette.css"
cat >"$palette" <<'EOF'
[data-theme="test-night"] {
  --accent: #e95678;
  --accent-light: #ec6a88;
  --text-primary: #d5d8da;
  --text-secondary: #bbbbbb;
  --text-tertiary: #6c6f93;
  --text-on-accent: #1c1e26;
  --background-solid: #1c1e26;
  --system-success: #29d398;
}
EOF
ansi="$test_root/Test Night"
printf '%s\n' 'palette = 2=#00ff00' 'palette = 5=#ff00ff' >"$ansi"

target="$test_root/themes/test-night.css"
typora_generate_theme "$palette" "$ansi" "" "test-night" "$target" \
  || fail "generation failed: $typora_theme_error"
rg -Fq 'Generated by set-theme.sh from test-night' "$target" || fail "missing header"
rg -Fq 'color-scheme: dark' "$target" || fail "dark palette not detected as dark"
rg -Fq -- '--bg-color: #1c1e26' "$target" || fail "background not applied"
rg -Fq -- '--primary-color: #e95678' "$target" || fail "accent not applied"
rg -Fq '.cm-s-inner .cm-string-2 { color: #00ff00; }' "$target" || fail "ANSI green not used for strings"
rg -Fq '.cm-s-inner .cm-keyword { color: #ff00ff; }' "$target" || fail "ANSI magenta not used for keywords"
rg -Fq 'night/mermaid.dark.css' "$target" || fail "dark theme lacks dark mermaid import"
# No placeholder may survive into the stylesheet.
! rg -q '\$[a-z_]+' "$target" || fail "unexpanded variable in output"

# Without a terminal palette, syntax colours fall back to the desktop palette.
fallback="$test_root/themes/fallback.css"
typora_generate_theme "$palette" "" "" "fallback" "$fallback" || fail "fallback generation failed"
rg -Fq '.cm-s-inner .cm-string-2 { color: #29d398; }' "$fallback" || fail "success colour not used as fallback"

light_palette="$test_root/light.css"
printf '%s\n' '--background-solid: #fafafa;' '--text-primary: #222222;' '--accent: #3366cc;' >"$light_palette"
light_target="$test_root/themes/light.css"
typora_generate_theme "$light_palette" "" "" "light" "$light_target" || fail "minimal light palette rejected"
rg -Fq 'color-scheme: light' "$light_target" || fail "light palette not detected as light"
! rg -Fq 'mermaid.dark.css' "$light_target" || fail "light theme imports dark mermaid"

missing_target="$test_root/themes/missing.css"
if typora_generate_theme "$test_root/no-such.css" "" "" "missing" "$missing_target"; then
  fail "missing palette was accepted"
fi
[[ ! -e "$missing_target" ]] || fail "missing palette left a file behind"
[[ "$typora_theme_error" == "palette not found:"* ]] || fail "wrong error: $typora_theme_error"

printf '%s\n' '--accent: #fff;' >"$test_root/malformed.css"
if typora_generate_theme "$test_root/malformed.css" "" "" "malformed" "$test_root/themes/malformed.css"; then
  fail "palette without background was accepted"
fi
[[ ! -e "$test_root/themes/malformed.css" ]] || fail "malformed palette left a file behind"

# --- Obsidian details ------------------------------------------------------

obsidian="$test_root/obsidian.css"
cat >"$obsidian" <<'EOF2'
.theme-dark {
  --h1-color: #111111;
  --h2-color: #222222;
  --bold-color: #333333;
  --italic-color: #444444;
  --link-external-color: #555555;
  --text-highlight-bg: rgba(250, 183, 149, 0.2);
  --code-normal: var(--color-cyan);
  --color-pink: #666666;
  --color-green: #777777;
}
EOF2
ob_target="$test_root/themes/obsidian.css"
typora_generate_theme "$palette" "$ansi" "$obsidian" "obsidian" "$ob_target" \
  || fail "generation with Obsidian theme failed: $typora_theme_error"
rg -Fq 'h1 { font-size: 1.802em; font-weight: 700; color: #111111; }' "$ob_target" || fail "h1 colour not from Obsidian"
rg -Fq 'h2 { font-size: 1.602em; color: #222222; }' "$ob_target" || fail "h2 colour not from Obsidian"
rg -Fq 'h3 { font-size: 1.424em; color: #d5d8da; }' "$ob_target" || fail "undefined heading colour did not fall back to text"
rg -Fq 'strong, b, th, dt { color: #333333;' "$ob_target" || fail "bold colour not from Obsidian"
rg -Fq 'em, i { color: #444444; }' "$ob_target" || fail "italic colour not from Obsidian"
rg -Fq 'color: #555555;' "$ob_target" || fail "link colour not from Obsidian"
rg -Fq 'background: rgba(250, 183, 149, 0.2);' "$ob_target" || fail "rgba highlight not carried over"
rg -Fq '.cm-s-inner .cm-keyword { color: #666666; }' "$ob_target" || fail "Obsidian pink not used for keywords"
rg -Fq '.cm-s-inner .cm-string-2 { color: #777777; }' "$ob_target" || fail "Obsidian green did not beat ANSI green"
# A computed value is skipped, not copied: code falls back to the red role.
! rg -Fq 'var(--color-cyan)' "$ob_target" || fail "computed Obsidian value leaked into output"
! rg -q '\$[a-z_]+' "$ob_target" || fail "unexpanded variable in output"

# --- Ghostty lookup -----------------------------------------------------------

HOME="$test_root/home"
mkdir -p "$HOME/.config/ghostty/themes"
touch "$HOME/.config/ghostty/themes/MapQuest" "$HOME/.config/ghostty/themes/mapquest-tabs.css"
[[ "$(typora_ghostty_theme_for mapquest)" == "$HOME/.config/ghostty/themes/MapQuest" ]] \
  || fail "mixed-case ghostty theme not found"
if typora_ghostty_theme_for nord >/dev/null; then
  fail "absent ghostty theme reported as found"
fi

TYPORA_OBSIDIAN_THEMES_DIR="$HOME/vault-themes"
mkdir -p "$TYPORA_OBSIDIAN_THEMES_DIR/Horizon Dark" "$TYPORA_OBSIDIAN_THEMES_DIR/Empty Theme"
touch "$TYPORA_OBSIDIAN_THEMES_DIR/Horizon Dark/theme.css"
[[ "$(typora_obsidian_theme_for horizon-dark)" == "$TYPORA_OBSIDIAN_THEMES_DIR/Horizon Dark/theme.css" ]] \
  || fail "Obsidian theme not found by slug"
if typora_obsidian_theme_for empty-theme >/dev/null; then
  fail "Obsidian theme dir without theme.css reported as found"
fi

# --- Profile selection ------------------------------------------------------

profile="$test_root/profile.data"
encode_json '{"version":"1.14.9","uuid":"abc","theme":"github.css","backgroundColor":"#FFFFFF","isDarkMode":false,"note":"café"}' >"$profile"

typora_select_theme "$profile" desktop "#1c1e26" || fail "select failed: $typora_theme_error"
json=$(decode "$profile")
[[ "$(jq -r .theme <<<"$json")" == desktop.css ]] || fail "theme not selected"
[[ "$(jq -r .backgroundColor <<<"$json")" == "#1C1E26" ]] || fail "background not recorded"
[[ "$(jq -r .isDarkMode <<<"$json")" == true ]] || fail "dark mode not recorded"
[[ "$(jq -r .uuid <<<"$json")" == abc ]] || fail "unrelated settings were lost"
[[ "$(jq -r .note <<<"$json")" == "café" ]] || fail "non-ASCII settings were corrupted"
[[ "$(typora_selected_theme "$profile")" == desktop.css ]] || fail "selected theme not read back"
# Typora's own format: one line of lowercase hex, no trailing newline.
[[ "$(cat "$profile")" =~ ^[0-9a-f]+$ ]] || fail "profile not hex-encoded"

[[ "$(stat -c %a "$profile" 2>/dev/null || stat -f %Lp "$profile")" == 644 ]] \
  || fail "profile permissions changed"

typora_publish_desktop "$test_root/themes" test-night || fail "desktop publish failed"
cmp -s "$target" "$test_root/themes/desktop.css" || fail "desktop theme differs from source"
[[ -z "$(find "$test_root/themes" -name '.*' -type f)" ]] || fail "temporary files left behind"

typora_select_theme "$profile" desktop "#fafafa" || fail "light select failed"
[[ "$(decode "$profile" | jq -r .isDarkMode)" == false ]] || fail "light theme recorded as dark"

# A running Typora would overwrite the profile on exit: refuse, and say so.
before=$(cat "$profile")
typora_theme_running() { return 0; }
set +e
typora_select_theme "$profile" other "#000000"
status=$?
set -e
typora_theme_running() { return 1; }
(( status == 2 )) || fail "running Typora not reported with status 2 (got $status)"
[[ "$(cat "$profile")" == "$before" ]] || fail "profile changed while Typora was running"

for bad in 'not hex at all' 'abc' '7b2274'; do
  printf '%s' "$bad" >"$profile"
  if typora_select_theme "$profile" desktop "#000000"; then
    fail "malformed profile accepted: $bad"
  fi
  [[ "$(cat "$profile")" == "$bad" ]] || fail "malformed profile was rewritten: $bad"
done

: >"$profile"
if typora_select_theme "$profile" desktop "#000000"; then
  fail "empty profile accepted"
fi

if typora_select_theme "$test_root/absent.data" desktop "#000000"; then
  fail "absent profile accepted"
fi
[[ ! -e "$test_root/absent.data" ]] || fail "absent profile was created"

echo "Typora theme tests passed"
