#!/usr/bin/env bash

set -euo pipefail

test_root=$(mktemp -d /tmp/youtube-music-theme.XXXXXX)

cleanup() {
  [[ "$test_root" == /tmp/youtube-music-theme.* ]] && rm -rf -- "$test_root"
}
trap cleanup EXIT

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
# shellcheck source=lib/theme-colors.sh
source "$script_dir/lib/theme-colors.sh"
# shellcheck source=lib/youtube-music-theme.sh
source "$script_dir/lib/youtube-music-theme.sh"

palette="$test_root/palette.css"
target="$test_root/YouTube Music Desktop App/theme.css"
cat >"$palette" <<'EOF'
:root {
  --background-solid: #101820;
  --accent: #80cbc4;
  --accent-light: #a7ded9;
  --text-primary: #f1f5f8;
  --text-secondary: #aab7c4;
}
EOF

youtube_music_generate_theme "$palette" "test-night" "dark" "$target"
[[ -f "$target" ]]
rg -Fq 'Generated by set-theme.sh from test-night' "$target"
rg -Fq 'color-scheme: dark' "$target"
rg -Fq -- '--desktop-theme-background: #101820' "$target"
rg -Fq -- '--desktop-theme-accent: #80cbc4' "$target"
rg -Fq 'ytmusic-player-bar' "$target"

light_target="$test_root/light.css"
youtube_music_generate_theme "$palette" "test-day" "light" "$light_target"
rg -Fq 'color-scheme: light' "$light_target"

missing_target="$test_root/missing.css"
if youtube_music_generate_theme "$test_root/no-such.css" "missing" "dark" "$missing_target"; then
  echo "missing palette was accepted" >&2
  exit 1
fi
[[ ! -e "$missing_target" ]]
[[ "$youtube_music_theme_error" == "palette not found:"* ]]

invalid_target="$test_root/invalid.css"
if youtube_music_generate_theme "$palette" "invalid" "sepia" "$invalid_target"; then
  echo "invalid color scheme was accepted" >&2
  exit 1
fi
[[ ! -e "$invalid_target" ]]

printf '%s\n' '--accent: #fff;' >"$test_root/malformed.css"
if youtube_music_generate_theme "$test_root/malformed.css" "malformed" "dark" "$test_root/malformed-target.css"; then
  echo "malformed palette was accepted" >&2
  exit 1
fi

echo "YouTube Music theme tests passed"
